### ISSUE TITLE
npm-start throws an error: "The specified procedure was not found."

### ISSUE THREAD

**Issue by draschke** [SAP-samples/sap-tech-bytes#4]
npm start throws an error.
PS C:\git\sap-tech-bytes\db> npm start

At this try catch statement, the hana-client index.js throws an error.  
```
db\node_modules\@sap\hdi-deploy\node_modules\@sap\hana-client\lib\index.js
        debug('... Looking for prebuilt copy in ' + driver_path + ' ... ');
        db = require(driver_path);
```

```
driver_path
'C:\git\sap-tech-bytes\db\node_modules\@sap\hdi-deploy\node_modules\@sap\hana-client\prebuilt\ntamd64-msvc2010\hana-client.node'
```

![image](https://user-images.githubusercontent.com/4199123/117797332-2c94a900-b250-11eb-87b7-902c5fa4e9ca.png)
```

C:\git\sap-tech-bytes\db\node_modules\@sap\hdi-deploy\node_modules\@sap\hana-client\lib\index.js:123
        throw ex;
        ^

Error: The specified procedure was not found.
\\?\C:\git\sap-tech-bytes\db\node_modules\@sap\hdi-deploy\node_modules\@sap\hana-client\prebuilt\ntamd64-msvc2010\hana-client.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1302:18)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (C:\git\sap-tech-bytes\db\node_modules\@sap\hdi-deploy\node_modules\@sap\hana-client\lib\index.js:115:14)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deploy@ start: `node node_modules/@sap/hdi-deploy/deploy.js`
npm ERR! Exit status 1
npm ERR!
```

Any ideas?

**Comment by draschke** [comment]
Sorry, I'm so stupid. Missed the step 'npm install'
Now it works.

**Comment by diraschk** [comment]
Hi Thomas, 
try to follow your sample, [cds build](https://youtu.be/CrhIfKvI1bs?t=839)

If I execute 'cds build' I don't get the db modul generated in folder srv. 
I can't find out, what step I missed.  Do you have an idea?

```
PS C:\git\sap-tech-bytes> cds build 
[cds] - determining build tasks for project [C:\git\sap-tech-bytes].
[cds] - the following build tasks have been auto-created and will be executed.
   {
     "build": {
       "target": "gen",
       "tasks": [
         {"for":"node-cf", "src":"srv", "options":{"model":["db","srv","app"]}}
       ]
     }
   }

[cds] - building project [C:\git\sap-tech-bytes], clean [true]


[cds] - done > wrote output to:
  gen\srv\.cfignore
  gen\srv\manifest.yml
  gen\srv\package.json
  gen\srv\srv\csn.json
```

The only thing what I'm wondering is the end after running **npm start** (Application can be stopped.). Not sure  if the deployment was successfully.
Deployment ended at 2021-05-12 09:24:24
(7s 921ms)
Application can be stopped.

**Comment by jung-thomas** [comment]
Which branch are you working with? I'm guessing its the HANA Existing CAP project  that you are working with:
https://github.com/SAP-samples/sap-tech-bytes/tree/2021-05-03-hana-existing-cap
Is that correct?
When I clone that branch and perform a cds build from the root of the project, it correctly processes both the /db and /srv contents:
![image](https://user-images.githubusercontent.com/12159356/117991735-54e1dd80-b30c-11eb-96bf-33a4dcfc44a6.png)

So assuming that we are both working from the same starting branch there must be some difference, but without knowing more what you have on your side its difficult to say. I'm not using any special build rules in the package.json, but you might compare your package.json to mine to see if there are differences.

**Comment by draschke** [comment]
I started with this branch.
https://github.com/SAP-samples/sap-tech-bytes/tree/2021-05-03-**hana-existing-starting**
I did it twice an came in both cases to the same issue.
at first I forked yours and tried it there and afterthat copied yours and tried it again.

compared your with mine output, I miss the task: **{"for":hana", "src":"db",..... }"**.
from my root
```
PS C:\git\dr-sap-tech-bytes> cds build
[cds] - determining build tasks for project [C:\git\dr-sap-tech-bytes].
[cds] - the following build tasks have been auto-created and will be executed.
   {
     "build": {
       "target": "gen",
       "tasks": [
         {"for":"node-cf", "src":"srv", "options":{"model":["db","srv","app"]}}
       ]
     }
   }

[cds] - building project [C:\git\dr-sap-tech-bytes], clean [true]
[cds] - cds [5.1.3], compiler [2.2.4], home [C:\git\dr-sap-tech-bytes\node_modules\@sap\cds]
[cds] - done > wrote output to:
  gen\srv\.cfignore
  gen\srv\manifest.yml
  gen\srv\package.json
  gen\srv\srv\csn.json

[cds] - build completed in: 241.942ms

```

**Comment by jung-thomas** [comment]
Well the https://github.com/SAP-samples/sap-tech-bytes/tree/2021-05-03-hana-existing-cap branch was created by taking the https://github.com/SAP-samples/sap-tech-bytes/tree/2021-05-03-hana-existing-starting branch and performing the manual steps I showed in the video. So the end result with those same steps should be the same. So somewhere something must have deviated.  When you look at the package.json in the root of the project does it look like the one in https://github.com/SAP-samples/sap-tech-bytes/tree/2021-05-03-hana-existing-cap ? By running the cds init and cds add commands from the video it should not only add the folders to the project but adjust the package.json.  

But I'm kind of wondering where you put the model.cds file in the /db folder. Is it right in the root of the /db folder?  Or perhaps you accidently put it in the /db/src folder.  That's an easy mistake to make and it would cause the cds build command to no longer find model.cds and produce an error.  But if that were the case I'm a little suprised the your /srv builds successfully. Becuase it should be referencing ,,/db/model.cds. https://github.com/SAP-samples/sap-tech-bytes/blob/2021-05-03-hana-existing-cap/srv/model-srv.cds#L5
If your model.cds was the wrong place I would expect you to get an error on the building of the service layer, but then again if it were in the right place the it should be picked up by cds build. 

But maybe just look at the structure of https://github.com/SAP-samples/sap-tech-bytes/tree/2021-05-03-hana-existing-cap side by side with your project structure and see if there are obvious differences.  Also compare the package.json in the root of both projects.  I'm guessing there is going to be some small difference.

**Comment by draschke** [comment]
> When you look at the package.json in the root of the project does it look like the one in https://github.com/SAP-samples/sap-tech-bytes/tree/2021-05-03-hana-existing-cap ?

your were right! now it works.
problem was that my package.json file looked different compared with yours. after using the package.json from  [2021-05-03-hana-existing-cap](https://github.com/SAP-samples/sap-tech-bytes/tree/2021-05-03-hana-existing-cap) as you said, I get the gen/db as expected.

**Comment by draschke** [comment]
Hi Thomas,

was struggling with [cds start](https://youtu.be/CrhIfKvI1bs?t=1183)

The issue was that the port was already used. 
To handle this issue I had to stop this service:
```
Windows
PS C:\git\priv> netstat -ano|findstr "PID :4004"
PS C:\git\priv> taskkill /pid 20080 /f
```

If you know a better way to solve this issue, please let me know.


This was the problem:
```
PS C:\git\dr-sap-tech-bytes> npm start

> hana-existing-cap@1.0.0 start C:\git\dr-sap-tech-bytes
> cds run


[cds] - model loaded from 2 file(s):

  .\db\model.cds
  .\srv\model-srv.cds

[cds] - connect to db > hana {}
[cds] - serving POService { at: '/po' }
[ERROR] listen EADDRINUSE: address already in use :::4004
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Function.listen (C:\git\dr-sap-tech-bytes\node_modules\express\lib\application.js:618:24)
    at cds_server (C:\git\dr-sap-tech-bytes\node_modules\@sap\cds\server.js:54:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async serve (C:\git\dr-sap-tech-bytes\node_modules\@sap\cds\bin\serve.js:174:18)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hana-existing-cap@1.0.0 start: `cds run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hana-existing-cap@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by draschke** [comment]
hi Thomas,
if I try to click on of the links from the service endpoints I get this issue.
**[cds] - VError: Found 0 matching services**
![image](https://user-images.githubusercontent.com/4199123/118266224-92846900-b4ba-11eb-8f4a-9cb5513eb868.png)

```
PS C:\git\dr-sap-tech-bytes> npm start

> hana-existing-cap@1.0.0 start C:\git\dr-sap-tech-bytes
> cds run


[cds] - model loaded from 2 file(s):

  .\db\model.cds
  .\srv\model-srv.cds

[cds] - connect to db > hana {}
[cds] - serving POService { at: '/po' }

[cds] - launched in: 823.1ms
[cds] - server listening on { url: 'http://localhost:4004' }
[ terminate with ^C ]

[cds] - GET /$fiori-preview/POService/POItems
[cds] - GET /appconfig/fioriSandboxConfig.json
[cds] - GET /$fiori-preview/POService/POItems/app/Component-preload.js
[cds] - GET /$fiori-preview/POService/POItems/app/Component-preload.js
[cds] - GET /$fiori-preview/POService/POItems/app/Component.js
[cds] - HEAD /po/0
[cds] - GET /po/$metadata
[cds] - GET /sap/bc/lrep/flex/data/preview.Component?sap-language=de-DE
[cds] - GET /sap/bc/lrep/flex/settings
[cds] - POST /po/$batch
[cds] - > READ POItems {
  '$count': 'true',
  '$select': 'CURRENCY,DELIVERYDATE,GROSSAMOUNT,NETAMOUNT,PRODUCTID,PURCHASEORDERID,QUANTITY,QUANTITYUNIT,TAXAMOUNT',
  '$skip': '0',
  '$top': '30'
}
[cds] - VError: Found 0 matching services
    at Object.serviceCredentials (C:\git\dr-sap-tech-bytes\node_modules\@sap\xsenv\lib\xsservices.js:109:11)   
    at singleTenantInstanceManager (C:\git\dr-sap-tech-bytes\node_modules\@sap\cds-runtime\lib\hana\pool.js:36:58)
    at credentials4 (C:\git\dr-sap-tech-bytes\node_modules\@sap\cds-runtime\lib\hana\pool.js:53:85)
    at C:\git\dr-sap-tech-bytes\node_modules\@sap\cds-runtime\lib\hana\pool.js:138:9
    at new Promise (<anonymous>)
    at pool4 (C:\git\dr-sap-tech-bytes\node_modules\@sap\cds-runtime\lib\hana\pool.js:137:7)
[cds] - VError: Found 0 matching services
    at Object.serviceCredentials (C:\git\dr-sap-tech-bytes\node_modules\@sap\xsenv\lib\xsservices.js:109:11)   
    at singleTenantInstanceManager (C:\git\dr-sap-tech-bytes\node_modules\@sap\cds-runtime\lib\hana\pool.js:36:58)
    at credentials4 (C:\git\dr-sap-tech-bytes\node_modules\@sap\cds-runtime\lib\hana\pool.js:53:85)
    at C:\git\dr-sap-tech-bytes\node_modules\@sap\cds-runtime\lib\hana\pool.js:138:9
    at new Promise (<anonymous>)
    at pool4 (C:\git\dr-sap-tech-bytes\node_modules\@sap\cds-runtime\lib\hana\pool.js:137:7)
    at Object.acquire (C:\git\dr-sap-tech-bytes\node_modules\@sap\cds-runtime\lib\hana\pool.js:193:26)
    at HanaDatabase.acquire (C:\git\dr-sap-tech-bytes\node_modules\@sap\cds-runtime\lib\hana\Service.js:131:28)    at HanaDatabase.begin (C:\git\dr-sap-tech-bytes\node_modules\@sap\cds-runtime\lib\db\Service.js:52:23)     
    at HanaDatabase.begin_and_dispatch [as dispatch] (C:\git\dr-sap-tech-bytes\node_modules\@sap\cds\lib\serve\Transaction.js:151:38) {
  jse_shortmsg: 'Found 0 matching services',
  jse_info: {},
  id: '1446282',
  level: 'ERROR',
  timestamp: 1620992100573
```

I saw that your hana json object was fullfilled. In my case is this json object empty. **[cds] - connect to db > hana {}**
My remote system is an op-premise system. Does it work only with CF?

**Comment by jung-thomas** [comment]
>The issue was that the port was already used.

So there default port of 4004 conflicts with something else on your system?  If so in the cds serve/run command you can use the option --port and specify a different port or choose port 0 and CAP will choose a random free port

**Comment by jung-thomas** [comment]
>if I try to click on of the links from the service endpoints I get this issue.
[cds] - VError: Found 0 matching services

CAP also needs a default-env.json in the root and/or the /srv folder depending upon how your project is structured.  It needs to be able to connect to HANA as well and it won't reuse any configuration file from the /db folder.  You cant' see it the sample code because gitignore filters out the default-env.json, but here is what my project looks like locally with the same default-env.json file in the /db folder and the root folder:
![image](https://user-images.githubusercontent.com/12159356/118272825-2e997a80-b491-11eb-94a3-990d9117546d.png)

**Comment by draschke** [comment]
Hi Thomas,
try to convert an older **existing mta-project** to the new CAPM.

I run in a certificate validation issue, when trying to deploy the db modul to the db.
**PS C:\git\t3e\db> npm start
_Connection failed (RTE:[300015] SSL certificate validation failed_**
Is there a way to suppress the certificate validation?

the sslValidateCertificate is already on false.
```
default-env.json 
"sslValidateCertificate": false,
```

npm install --> works!
hana-cli status --> works!
hana-cli status -a  --> works!
```
PS C:\git\t3e\db> npm start

> deploy@ start C:\git\t3e\db
> node node_modules/@sap/hdi-deploy/deploy.js  --auto-undeploy

@sap/hdi-deploy, version 4.0.5 (mode default), server version unknown (0.0.0.0), node version 14.8.0, HDI version -1, container API version -1
Deployment started at 2021-05-18 14:29:05
Detection of server version failed; root cause: Connection failed (RTE:[300015] SSL certificate validation failed: 
Die Zertifikatkette wurde von einer nicht vertrauenswürdigen Zertifizierungsstelle ausgestellt.
 (host:port))
Detection of container API version failed; root cause: Connection failed (RTE:[300015] SSL certificate validation failed: Die Zertifikatkette wurde von einer nicht vertrauenswürdigen Zertifizierungsstelle ausgestellt.
 (host:port))
Detection of HDI version failed; root cause: Connection failed (RTE:[300015] SSL certificate validation failed: Die Zertifikatkette wurde von einer nicht vertrauenswürdigen Zertifizierungsstelle ausgestellt.
 (host:port))
Using default environment variables from file "default-env.json"
The server does not support live updating of make messages. The messages will be displayed, when the make is done. 
No ignore file at C:\git\t3e\db\.hdiignore.
Collecting files...
Collecting files... ok (0s 81ms)
19 directories collected
734 files collected
0 reusable modules collected
Target service: DIRASCHK-xqqrzopj5lywap2p-tbase-hdi-container
Could not check if session variable APPLICATION is set correctly: Connection failed (RTE:[300015] SSL certificate validation failed: Die Zertifikatkette wurde von einer nicht vertrauenswürdigen Zertifizierungsstelle ausgestellt.  
 (host:port))
Could not determine status of last build: Connection failed (RTE:[300015] SSL certificate validation failed: Die Zertifikatkette wurde von einer nicht vertrauenswürdigen Zertifizierungsstelle ausgestellt.
 (host:port))
Processing revoke files...
Processing revoke files... ok (0s 1ms)
Processing grants files...
Processing grants files... ok (0s 1ms)
Preprocessing files...
Preprocessing files... ok (0s 5ms)
Connecting to the container "TBASE_HDI_CONTAINER_3"...
Deployment to container TBASE_HDI_CONTAINER_3 failed - error: Connection failed (RTE:[300015] SSL certificate validation failed: Die Zertifikatkette wurde von einer nicht vertrauenswürdigen Zertifizierungsstelle ausgestellt. (host:port)) [Deployment ID: none].
Deployment ended at 2021-05-18 14:29:05
Error: Connection failed (RTE:[300015] SSL certificate validation failed: Die Zertifikatkette wurde von einer nicht vertrauenswürdigen Zertifizierungsstelle ausgestellt.
 (host:port))
(1s 20ms)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deploy@ start: `node node_modules/@sap/hdi-deploy/deploy.js  --auto-undeploy`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deploy@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\diraschk\AppData\Roaming\npm-cache\_logs\2021-05-18T12_29_05_965Z-debug.log
```

**Comment by draschke** [comment]
got it solved, by setting ecrypt to false. 
(tried it before, but it didn't work before for me) 
```
default-env.json 
"encrypt": false, 
```

**Comment by draschke** [comment]
Hi Thomas, 
in our own project we use the grantor file .hdbgrants  (db\cfg\TBRS_CSP.hdbgrants).
If I build the db folder I get this error:

```
PS C:\git\t3e\db> npm start
make in the container "TBASE_HDI_CONTAINER_3" with 0 files to deploy, 0 files to undeploy... ok.
Processing revoke files...
Processing revoke files... ok (0s 0ms)
Processing grants files...
 Processing "cfg/TBRS_CSP.hdbgrants"...
Deployment ended at 2021-05-18 18:44:13
Error: service TBRS_CSP-grantor not found; the service definition does not exist.
(1s 980ms)
```
I know that this service exists and it is working for our other projects.
Any idea whats wrong with it?

I tried to find out more by using this commands, but I didn't work for me.

```
PS C:\git\t3e\db> hana-cli ups --cf 
Connection Problems:  Error: Connection Problems:  {"killed":false,"code":1,"signal":null,"cmd":"cf curl \"/v3/service_instances?space_guids=&organization_guids=&type=user-provided\"","stdout":"FEHLGESCHLAGEN\nKein API-Endpunkt festgelegt. Verwenden 
Sie 'cf login' oder 'cf api', um einen Endpunkt als Ziel auszuwählen.\n","stderr":""}
PS C:\git\t3e\db> hana-cli ups --cf -a
Connection Problems:  Error: Connection Problems:  {"killed":false,"code":1,"signal":null,"cmd":"cf curl \"/v3/service_instances?space_guids=&organization_guids=&type=user-provided\"","stdout":"FEHLGESCHLAGEN\nKein API-Endpunkt festgelegt. Verwenden 
Sie 'cf login' oder 'cf api', um einen Endpunkt als Ziel auszuwählen.\n","stderr":""}
```

**Comment by jung-thomas** [comment]
>I know that this service exists and it is working for our other projects.
>Any idea whats wrong with it?

It's important to understand what is happening when you deploy normally and when using the hdi-deploy module directly.

When you press build/deploy from the SAP Web IDE for SAP HANA - a lot happens.  The db module is itself deployed as a Node.js application to xs/cf runtime.  Then the mta.yaml is read to see the service bindings.  These service bindings (and the connection details and credentials they carry) are all imported into the environment of the db module service. This is how the hdi-deploy module processes. It only ever reads from the environment. It doesn't actually know anything about the mta.yaml file nor does it ever read anything from there.  It's only the binding to the service that supplies these details. 

So when you run the hdi-deploy module directly (as you would in local VSCode development or in the Business Application Studio), it happens much faster but that's because it doesn't need to deploy the deployer node.js application to xs/cf. But this also means that there is no environment setup from service bindings (because there are no service bindings). 

This is why we use the default-env.json. It simulates the service bindings and loads them into the environment of any application/module that uses @sap/xsenv to read the environment. This way we simulate how things will work when actually running from xs/cf runtime without having to take the time to actually deploy and create bindings.

Now we come to your specific situation.  When using hdbgrants you need access to the user provided services (and their details) at deploy time. This means all of this content needs to be added to your default-env.json as well. It doesn't matter that the services exists or that they are properly setup in the mta.yaml. The HDI deploy process used by the hdi-deploy module directly (and therefore how the Business Application Studio works now too) needs either a .env or default-env.json to include all service details - the primary HDI and any user provided services as well.

For more details and an example, have a look at this video 
https://www.youtube.com/watch?v=9MKZhHg-y7s&list=PL6RpkC85SLQAHZ_V3cZsTok0T6BvI4HT1&index=7

**Comment by draschke** [comment]
> This means all of this content needs to be added to your default-env.json as well.

This is exactly what I was thinking about, but didn't believe, if it would work. 


Thanks for this video link and your great help! Now it works!
(After I got it to work, I realized that I could also get the environment from the di-builder (xs env di-builder)
Wasn't aware of it, that it is bound to the di-builder.)

**Comment by jung-thomas** [comment]
Yes actually in XSA to avoid deploying lots of redundant copies of the hdi-deploy module, there is one central copy and that is the di-builder.  But it does mean that it needs the bindings and environment for everything you need to build in your development space.  But this really the sole purpose of the di-builder.
